<html><body><div><div class="blog-content">

                        

                            
                        



                        
                            
                                <h2 id="_1">Введение</h2>
<p>В этом уроке вы узнаете о важном средстве языка, без которого крупная программа не может обойтись. Речь пойдет об исключениях. Что это такое, как ими пользоваться и как создавать собственные?</p>
<p>Исключительные ситуации или исключения(exceptions) - это ошибки, обнаруженные при исполнении.  Например, к чему приведет попытка чтения несуществующего файла? Или если файл был случайно удален пока программа работала? Такие ситуации обрабатываются при помощи исключений.</p>
<p>Если же Python не может понять, как обойти сложившуюся ситуацию, то ему не остается ничего кроме как поднять руки и сообщить, что обнаружил ошибку.</p>
<p>В общем, исключения необходимы, чтобы сообщать программисту об ошибках.</p>
<p>Простейший пример исключения - деление на ноль:</p>
<div class="codehilite"><pre><span class="mi">100</span> <span class="o">/</span> <span class="mi">0</span>

<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">""</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span>
    <span class="mi">100</span> <span class="o">/</span> <span class="mi">0</span>
<span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>
</pre></div>


<p>В данном случае интерпретатор сообщил нам об исключении ZeroDivisionError - делении на ноль. </p>
<h2 id="traceback">Traceback</h2>
<p>В большой программе исключения часто возникают внутри. Чтобы упростить программисту понимание ошибки и причины такого поведения Python предлагает Traceback или в сленге - трэйс. Каждое исключение содержит краткую информацию, но при этом полную, информацию о месте появления ошибки. По трэйсу найти и исправить ошибку становится проще.</p>
<p>Рассмотрим такой пример:</p>
<div class="codehilite"><pre><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">"/home/username/Develop/test/app.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">862</span><span class="p">,</span> <span class="ow">in</span> <span class="n">_handle</span>
    <span class="k">return</span> <span class="n">route</span><span class="o">.</span><span class="n">call</span><span class="p">(</span><span class="o">**</span><span class="n">args</span><span class="p">)</span>
  <span class="n">File</span> <span class="s">"/home/username/Develop/test/app.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1729</span><span class="p">,</span> <span class="ow">in</span> <span class="n">wrapper</span>
    <span class="n">rv</span> <span class="o">=</span> <span class="n">callback</span><span class="p">(</span><span class="o">*</span><span class="n">a</span><span class="p">,</span> <span class="o">**</span><span class="n">ka</span><span class="p">)</span>
  <span class="n">File</span> <span class="s">"/home/username/Develop/test/__init__.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">76</span><span class="p">,</span> <span class="ow">in</span> <span class="n">wrapper</span>
    <span class="n">body</span> <span class="o">=</span> <span class="n">callback</span><span class="p">(</span><span class="o">*</span><span class="n">args</span><span class="p">,</span> <span class="o">**</span><span class="n">kwargs</span><span class="p">)</span>
  <span class="n">File</span> <span class="s">"/home/username/Develop/test/my_app.py"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">16</span><span class="p">,</span> <span class="ow">in</span> <span class="n">index</span>
    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s">'test exception'</span><span class="p">)</span>
</pre></div>


<p>В данном примере четко видно, какой путь исполнения у программы. Смотрим снизу вверх и по шагам пониманием, как же мы докатились до такого исключения.</p>
<p>Рассмотрим какие еще встречаются комментарии к исключениям:</p>
<div class="codehilite"><pre><span class="mi">2</span> <span class="o">+</span> <span class="s">'1'</span>

<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">""</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span>
    <span class="mi">2</span> <span class="o">+</span> <span class="s">'1'</span>
<span class="ne">TypeError</span><span class="p">:</span> <span class="n">unsupported</span> <span class="n">operand</span> <span class="nb">type</span><span class="p">(</span><span class="n">s</span><span class="p">)</span> <span class="k">for</span> <span class="o">+</span><span class="p">:</span> <span class="s">'int'</span> <span class="ow">and</span> <span class="s">'str'</span>
</pre></div>


<p>В данном примере при попытке сложить целое число и строку мы получаем исключение TypeError. В описании сразу же становится ясно, что же мы не так написали.</p>
<div class="codehilite"><pre><span class="nb">int</span><span class="p">(</span><span class="s">'qwerty'</span><span class="p">)</span>

<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">""</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span>
    <span class="nb">int</span><span class="p">(</span><span class="s">'qwerty'</span><span class="p">)</span>
<span class="ne">ValueError</span><span class="p">:</span> <span class="n">invalid</span> <span class="n">literal</span> <span class="k">for</span> <span class="nb">int</span><span class="p">()</span> <span class="k">with</span> <span class="n">base</span> <span class="mi">10</span><span class="p">:</span> <span class="s">'qwerty'</span>
</pre></div>


<p>Приведение строчки к целому числу приводит к исключению ValueError.</p>
<p>В трэйсе этих двух примеров можно прочесть, что в таком-то файле на такой-то строчке есть ошибки.</p>
<p>На этом список встроенных исключений не заканчивается, в следующем разделе рассмотрены основные исключения и причины их возникновения.</p>
<h2 id="_2">Иерархия исключений</h2>
<p>Исключение, которое вы не увидите при выполнении кода - это BaseException - базовое исключение, от которого берут начало остальные.</p>
<p>В иерархии исключений две основные группы:</p>
<ul>
<li>Системные исключения и ошибки</li>
<li>Обыкновенные исключения</li>
</ul>
<p>Если обработку первых лучше не делать (если и делать, то надо четко понимать для чего), то обработку вторых целиком и полностью Python возлагает на плечи программиста.</p>
<p>К системным можно смело отнести:</p>
<ul>
<li>SystemExit - исключение, порождаемое функцией sys.exit при выходе из программы.</li>
<li>KeyboardInterrupt - возникает при прерывании программы пользователем (обычно сочетанием клавиш Ctrl+C).</li>
<li>GeneratorExit — возникает при вызове метода close объекта generator.</li>
</ul>
<p>Остальные исключения это "обыкновенные". Спектр уже готовых исключений велик.</p>
<p>Для Python2 иерархию исключений можно представить так:</p>
<p><a href="http://i.imgur.com/2755APp.png"><img alt="Python 2 Exception" src="http://i.imgur.com/xUXKwE7.png" title="Исключения в Python3"/></a></p>
<p>Список исключений покрывает большой объем ситуаций и ошибок программиста. Если предупреждения (warning) только просят обратить внимание, то ошибки уже могут остановить исполнение программы.</p>
<p>В Python3 появились новые исключения и иерархия стала такова:</p>
<p><a href="http://i.imgur.com/AenGQYk.png"><img alt="Python3 Exception" src="http://i.imgur.com/0daAbRa.png" title="Исключения в Python3"/></a></p>
<p>В целом заметно, что при создании Python3 добавлен блок новых исключений. Но даже этих почти 70 исключений не хватает при написании программ на языке Python. </p>
<h2 id="_3">Использование исключений</h2>
<p>Мы рассмотрели что такое исключения, какие они бывают и как их анализировать. Но до сих пор явно не рассмотрели такую важную вещь, как их использование.</p>
<p>Начнем с обработки.</p>
<h3 id="_4">Обработка исключений</h3>
<p>Давайте рассмотрим случай с делением на 0.</p>



<p>Данный код приведет к исключению ZeroDivisionError. Чтобы этого не случилось, воспользуемся конструкцией try..except, например так:</p>
<div class="codehilite"><pre><span class="k">try</span><span class="p">:</span>
    <span class="n">a</span> <span class="o">=</span> <span class="mi">100</span>
    <span class="n">b</span> <span class="o">=</span> <span class="mi">0</span>
    <span class="n">c</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
<span class="k">except</span> <span class="ne">ZeroDivisionError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre></div>


<p>Если исполнить этот код, то на консоль будет выведена  строка "<em>integer division or modulo by zero</em>". Казалось бы, что толком ничего это нам не дало, ошибка все также есть. Однако в блок except можно поместить обработку.</p>
<p>Например, мы условились, что значение переменной <em>c</em> в случае ошибки деления равно -1. Тогда модифицируем код:</p>
<div class="codehilite"><pre><span class="k">try</span><span class="p">:</span>
    <span class="n">a</span> <span class="o">=</span> <span class="mi">100</span>
    <span class="n">b</span> <span class="o">=</span> <span class="mi">0</span>
    <span class="n">c</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
<span class="k">except</span> <span class="ne">ZeroDivisionError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="n">c</span> <span class="o">=</span> <span class="o">-</span><span class="mi">1</span>
</pre></div>


<p>Перед тем как идти дальше, рассмотрим еще одну возможность.</p>
<p>Пускай у нас файл с данными в файловой системе и необходимо его прочитать. В этом случае сразу же всплывают несколько исключительных ситуаций, такие как: нет файла, файл битый; файл пустой (по заданию мы знаем, что в нем данные) и другие.</p>
<p>Используя исключения, можно вот так решить эту задачу:</p>
<div class="codehilite"><pre><span class="k">try</span><span class="p">:</span>
    <span class="n">filepath</span> <span class="o">=</span> <span class="s">'test_file.txt'</span>
    <span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">filepath</span><span class="p">,</span> <span class="s">'r'</span><span class="p">)</span> <span class="k">as</span> <span class="n">fio</span><span class="p">:</span>
        <span class="n">result</span> <span class="o">=</span> <span class="n">fio</span><span class="o">.</span><span class="n">readlines</span><span class="p">()</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="n">result</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s">"File is empty"</span><span class="p">)</span>

<span class="k">except</span> <span class="ne">IOError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="n">result</span> <span class="o">=</span> <span class="p">[]</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="n">result</span> <span class="o">=</span> <span class="p">[]</span>
    <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre></div>


<p>В данном вымышленном коде новый ход - перехват нескольких видов исключений. Когда исключение брошено, оно сравнивается сверху вниз с каждым типом, пока не найдено совпадение. Если совпадения нет, то исключение пойдет наверх по цепочке исполнения кода.</p>
<p>Если обработка для разных типов исключений одинакова, то уменьшить количество кода становится не проблемой:</p>
<div class="codehilite"><pre><span class="k">try</span><span class="p">:</span>
    <span class="n">your_code</span>
<span class="k">except</span> <span class="p">(</span><span class="ne">IOError</span><span class="p">,</span> <span class="ne">Exception</span><span class="p">)</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre></div>


<h3 id="_5">Вызов исключений</h3>
<p>При работе с исключениями программист тратит большую часть времени на обработку, но при этом возникают ситуации, когда исключениями надо и бросать в других.</p>
<p>На сленге программистов "бросить исключение" означает написать код, который при исполнении будет инициировать исключительную ситуацию.</p>
<p>Например, функция, которая решает квадратное уравнение. Вы условились, что корни только вещественные, тогда в случае комплексных корней стоит бросить исключение.</p>
<p>Чтобы бросить исключение необходимо воспользоваться <strong>raise</strong></p>
<p>Пример:</p>
<div class="codehilite"><pre><span class="k">raise</span> <span class="ne">IOError</span><span class="p">(</span><span class="s">"текст исключения"</span><span class="p">)</span>
</pre></div>


<p>где IOError это класс исключения. </p>
<p>Если при обработке исключения вы желаете пробросить его еще выше, то следует написать такой код:</p>
<div class="codehilite"><pre><span class="k">try</span><span class="p">:</span>
    <span class="n">your_code</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">raise</span>
</pre></div>


<h3 id="_6">Собственные исключения</h3>
<p>При написании собственных программ разумное желание добавить выразительности коду, а так же обратить других программистов на особые исключительные ситуации. Для решения этой задачи стоит использовать собственные исключения.</p>
<p>В минимальном исполнении необходимо наследоваться от какого-нибудь класса в иерархии исключений. Например так:</p>
<div class="codehilite"><pre><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="k">pass</span>
</pre></div>


<p>Тогда можно бросить свое исключение:</p>
<div class="codehilite"><pre><span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="ne">Exception</span><span class="p">)</span>
</pre></div>


<p>Легко заметить, мы создаем класс, а значит все, что мы знаем о классах справедливо и для исключений. Можно завести переменные и делать их обработку. 
Как правило, исключения это очень маленькие классы. Они должны выполняться максимально быстро.</p>
<h2 id="tryexcept">Дополнение: Полная форма try..except</h2>
<p>Форма try...except не полная, полной же является try..except..else..finaly.</p>
<p>Применение полной конструкции может заметно упростить код, а также сделать его более безопасным.
Представим, что в программе происходит чтение файла и необходимо убедиться, что объект файла был корректно закрыт и что не возникло никакого исключения. Этого можно достичь с применением блока finally.</p>
<p>Иными словами, finally выполняет блок инструкций в любом случае, было ли исключение, или нет. А инструкция else выполняется в том случае, если исключения не было.</p>
<p>В целом, использование полной формы таково:</p>
<div class="codehilite"><pre><span class="k">try</span><span class="p">:</span>
    <span class="err">исполяем</span> <span class="err">какой</span><span class="o">-</span><span class="err">то</span> <span class="err">код</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="err">обработка</span> <span class="err">исключения</span>
<span class="k">else</span><span class="p">:</span>
    <span class="err">код</span><span class="p">,</span> <span class="err">который</span> <span class="err">будет</span> <span class="err">исполнен</span> <span class="err">в</span> <span class="err">случае</span><span class="p">,</span> <span class="err">когда</span> <span class="err">не</span> <span class="err">возникает</span> <span class="err">исключения</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="err">код</span><span class="p">,</span> <span class="err">который</span> <span class="err">гарантированно</span> <span class="err">будет</span> <span class="err">исполнен</span> <span class="err">последним</span> <span class="p">(</span><span class="err">всегда</span> <span class="err">исполняется</span><span class="p">)</span>
</pre></div>


<h2 id="_7">Выводы</h2>
<p>В уроке рассмотрены вопросы связанные с исключениями:</p>
<ul>
<li>Что такое исключение</li>
<li>Какие типы исключений присутствуют в языке</li>
<li>Как обрабатывать исключения</li>
<li>Как вызвать исключения</li>
<li>Как создавать собственные исключения</li>
</ul>
                            
                        



                        

                            
                            <footer class="post-info">
                                <span class="label label-default">Дата</span>
                            <span class="published">
                                <i class="fa fa-calendar"/><time>
                                2016-01-29 17:32:30</time>
                            </span>


                                <span class="label label-default">Категории</span>

                                
                                    
                                        
                                            <a href="/blog/category/python-%D1%83%D1%80%D0%BE%D0%BA%D0%B8/">Python уроки</a>
                                            , 
                                        
                                            <a href="/blog/category/%D1%83%D1%80%D0%BE%D0%BA%D0%B8-python/">Уроки Python</a>
                                            , 
                                        
                                            <a href="/blog/category/uchebnye-materialy/">Учебные материалы</a>
                                            
                                        
                                    
                                


                                <span class="label label-default">Теги</span>

                                

                            </footer>
                        


                        
                            
                        

                        
                            
                            <a class="btn btn-sm share-twitter" target="_blank" href="http://twitter.com/home?status=https%3A//pynsk.ru/blog/2016/01/29/lesson_exceptions/%20Python%20%D1%83%D1%80%D0%BE%D0%BA%D0%B8%3A%20%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%28exceptions%29">Опубликовать в Twitter</a>
                            <a class="btn btn-sm share-facebook" target="_blank" href="http://facebook.com/sharer.php?u=https://pynsk.ru/blog/2016/01/29/lesson_exceptions/&amp;t=Python%20%D1%83%D1%80%D0%BE%D0%BA%D0%B8%3A%20%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%28exceptions%29">Опубликовать в Facebook</a>
                        

                        
                            
                        

                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        


                        <hr/>
                        
                        <hr/>

                        
                            

            </div>

        </div></body></html>