<html><body><div><div class="post-text" itemprop="text">

<p>So I have this piece of Python 3 code:</p>

<pre><code>import socket
s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
s.bind(('eth0', 0))
s.send(eth_packet)
</code></pre>

<p>This code works on my Raspberry Pi, but not on my external server. When I try to run it on my external server i get:</p>

<pre><code># sudo python3 test.py
s.send(eth_packet)
socket.error: [Errno 19] No such device
</code></pre>

<p>And I checked the network interfaces output (via an python script):
External server (debian):</p>

<pre><code>['lo [index=1, IPv4=127.0.0.1, IPv6=::1]', 'eth0:0 [index=2, IPv4=xxxxx, IPv6=None]', 'eth0 [index=2, IPv4=yyyyyy, IPv6=zzzzzzz]']
</code></pre>

<p>Raspberry pi:</p>

<pre><code>['lo [index=1, IPv4=127.0.0.1, IPv6=None]', 'eth0 [index=2, IPv4=rrrrr, IPv6=None]']
</code></pre>

<p>Can someone explain what is going on? I just want to send a handcrafted message but this error keeps bugging me, can this be a problem with the drivers of my server? This is the same result as ifconfig.</p>

<p><strong>Edit</strong></p>

<p>Ok, i used strace for this example:</p>

<pre><code>#!/usr/bin/env python3

import socket
import binascii
import struct

test= '000a959d6816'
packet= struct.pack("!6s", binascii.unhexlify(bytes(test, 'UTF-8')))
s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
s.bind(('eth0', 0))
s.send(packet)
</code></pre>

<p>And this is the important part about strace:</p>

<pre><code>socket(PF_PACKET, SOCK_RAW, 0)          = 3
ioctl(3, SIOCGIFINDEX, {ifr_name="eth0", ifr_index=2}) = 0
bind(3, {sa_family=AF_PACKET, proto=0000, if2, pkttype=PACKET_HOST, addr(0)={0, }, 20) = 0
sendto(3, "\0\n\225\235h\26", 6, 0, NULL, 0) = -1 ENXIO (No such device or address)
open("test.py", O_RDONLY)               = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=247, ...}) = 0
ioctl(4, SNDCTL_TMR_TIMEBASE or TCGETS, 0x7fff86c5f090) = -1 ENOTTY (Inappropriate ioctl for device)
fstat(4, {st_mode=S_IFREG|0644, st_size=247, ...}) = 0
lseek(4, 0, SEEK_CUR)                   = 0
dup(4)                                  = 5
fcntl(5, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fstat(5, {st_mode=S_IFREG|0644, st_size=247, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc1251c2000
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "#!/usr/bin/env python3\n\nimport s"..., 4096) = 247
close(5)                                = 0
munmap(0x7fc1251c2000, 4096)            = 0
lseek(4, 0, SEEK_SET)                   = 0
lseek(4, 0, SEEK_CUR)                   = 0
read(4, "#!/usr/bin/env python3\n\nimport s"..., 4096) = 247
close(4)                                = 0
write(2, "Traceback (most recent call last"..., 143Traceback (most recent call last):
  File "test.py", line 11, in &lt;module&gt;
    s.send(packet)
socket.error: [Errno 6] No such device or address
) = 143
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fc1264050a0}, {0x428787, [], SA_RESTORER, 0x7fc1264050a0}, 8) = 0
close(3)                                = 0
</code></pre>
    </div>
    </div></body></html>