<html><body><div><div class="post-text" itemprop="text">

<p>Hello I am using supervisor with celery in order to run some tasks in a django web application.  Celery seems to be having an issue finding/resolving, models from packages that have been installed directly via github.</p>

<p><a href="http://pip.readthedocs.org/en/stable/reference/pip_install/#vcs-support" rel="nofollow">http://pip.readthedocs.org/en/stable/reference/pip_install/#vcs-support</a></p>

<p>As that states the packages are installed/cloned into a /src directory.  I am wondering if I am missing something in my environment setup with supervisord.conf file such as the PYTHONPATH or something else to have these installed packages available.  I am getting a ValueError: Related model cannot be resolved, which does not seem to make sense as the  application as a whole is working fine with these packages.</p>

<p><strong>Versions</strong></p>

<p>Celery -  3.1.18</p>

<p>Supervisor - 3.0b2</p>

<p><strong>supervisord.conf</strong></p>

<pre><code>[program:celeryd]
command=/home/path/to/virtualenv/celery worker -A moi --loglevel=info
stdout_logfile=/var/log/celery/celeryd.log
stderr_logfile=/var/log/celery/celeryd.error.log
directory=/path/to/app
</code></pre>

<p><strong>The virtualenv looks structure looks like this</strong></p>

<pre><code>virtualenv/
  - bin/
  - lib/
  - share/
  - src/github-installed-egg
</code></pre>

<p><strong>Error</strong></p>

<pre><code>File "/home/ubuntu/moi/lib/python3.4/site-packages/django/db/models/fields/related.py", line 1600, in resolve_related_fields
raise ValueError('Related model %r cannot be resolved' % self.rel.to)
ValueError: Related model 'ndptc_core_courses.Course' cannot be resolved
</code></pre>

<p>The web application is running using nginx and uwsgi, and works fine .  The virtualenv setting in the uwsgi configuration file makes this work.  The model is a foreign key that is declared by name and not the model object itself.  Models that are from packages installed via pypi work fine as well its just those installed in the src folder that are causing the issue.</p>

<p><a href="https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey" rel="nofollow">described in django docs here</a></p>
    </div>
    </div></body></html>