<html><body><div><div class="post-text" itemprop="text">

<p>I have a package with a rather extensive test suite, which I maintain with very low frequency of changes. From a time to time I forget to install a component needed for testing or that my changes break the test code. And very often when this happens, <code>setuptools</code> causes a hiding of the real cause of the problem.  </p>

<p>Here is an example:</p>

<pre><code>$ python setup.py test
running test
running egg_info
writing requirements to pwman3.egg-info/requires.txt
writing pwman3.egg-info/PKG-INFO
writing top-level names to pwman3.egg-info/top_level.txt
writing dependency_links to pwman3.egg-info/dependency_links.txt
writing entry points to pwman3.egg-info/entry_points.txt
reading manifest file 'pwman3.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pwman3.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 361, in &lt;module&gt;
    'console_scripts': ['pwman3 = pwman.ui.cli:main']
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/test.py", line 146, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/test.py", line 127, in with_project_on_sys_path
    func()
  File "/usr/lib64/python2.7/site-packages/setuptools/command/test.py", line 167, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_pwman'
</code></pre>

<p>Sometimes, I spend a few frustrating minutes trying to understand why I get this error, despite have a python module called <code>test_pwman</code> inside the test directory.</p>

<p>The relevant code inside <code>setup.py</code> is:</p>

<pre><code>from setuptools.command.install import install

setup(name=pwman.appname,
      ...
      test_suite='tests.test_pwman.suite',
      ...
      )
</code></pre>

<p>After spending some time staring at the screen, I would remember I can run the test suite like this:</p>

<pre><code>$ python -m tests.test_pwman
</code></pre>

<p>Which reveals, for example a real cause for tests not running:</p>

<pre><code>Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ozn/Software/pwman3/tests/test_pwman.py", line 27, in &lt;module&gt;
    from .test_postgresql import TestPostGresql
  File "tests/test_postgresql.py", line 26, in &lt;module&gt;
    import psycopg2 as pg
  File "/home/ozn/.virtualenvs/pwman3/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in &lt;module&gt;
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: libpq.so.5: cannot open shared object file: No such file or directory
</code></pre>

<p>After installing Postgresql with Python support, I could run my tests. So my question is:</p>

<p>How do you cause setuptools to propagate the real exception?<br/>
Is my code calling the test suite from <code>setup.py</code> wrong? </p>
    </div>
    </div></body></html>